feat: add filter command

diff --git a/recipe b/recipe
--- a/recipe
+++ b/recipe
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.0.5 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.1.1 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
@@ -44,6 +44,7 @@ recipe_usage() {
   printf "  %s   Show the content of a recipe\n" "show  "
   printf "  %s   Update recipe to the latest version\n" "update"
   printf "  %s   Show recipe book directory\n" "dir   "
+  printf "  %s   Interactively filter recipes\n" "filter"
   echo
 
   if [[ -n $long_usage ]]; then
@@ -632,6 +633,42 @@ recipe_dir_usage() {
   fi
 }
 
+recipe_filter_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "recipe filter - Interactively filter recipes\n"
+    echo
+
+  else
+    printf "recipe filter - Interactively filter recipes\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  recipe filter [VALUE]\n"
+  printf "  recipe filter --help | -h\n"
+  echo
+
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+    printf "%s\n" "Arguments:"
+
+    printf "  %s\n" "VALUE"
+    printf "    Value used to filter recipe names\n"
+    echo
+
+    printf "%s\n" "Examples:"
+    printf "  recipe filter\n"
+    echo
+
+  fi
+}
+
 normalize_input() {
   local arg flags
 
@@ -745,7 +782,7 @@ filter_recipe_book_not_empty() {
 
 find_recipe() {
     run_silent pushd "${RECIPE_BOOK_DIR}"
-    local recipes=`\fd --exclude '.gitignore' --exclude '.templates' -c 'never' -H -t f`
+    local recipes=`\fd --exclude '.gitignore' --color=never --hidden --type=f`
 
     run_silent popd
     if [[ -n "${recipes}" ]]; then
@@ -1096,6 +1133,19 @@ recipe_dir_command() {
 
 }
 
+recipe_filter_command() {
+  local value=${args['value']}
+
+  local recipes="$(find_recipe)"
+
+  if [[ -n "${value}" ]]; then
+      echo "${recipes}" | \rg $value --color=never
+  else
+      echo "${recipes}" | gum filter --placeholder "Select a recipe..."
+  fi
+
+}
+
 parse_requirements() {
 
   while [[ $# -gt 0 ]]; do
@@ -1256,6 +1306,13 @@ parse_requirements() {
       action="dir"
       shift
       recipe_dir_parse_requirements "$@"
+      shift $#
+      ;;
+
+    filter)
+      action="filter"
+      shift
+      recipe_filter_parse_requirements "$@"
       shift $#
       ;;
 
@@ -2136,6 +2193,58 @@ recipe_dir_parse_requirements() {
 
 }
 
+recipe_filter_parse_requirements() {
+
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        recipe_filter_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  action="filter"
+
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+
+        if [[ -z ${args['value']+x} ]]; then
+
+          args['value']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
+
+        ;;
+
+    esac
+  done
+
+  filter_error=$(filter_recipe_book_healthy)
+  if [[ -n $filter_error ]]; then
+    echo "$filter_error" >&2
+    exit 1
+  fi
+
+}
+
 initialize() {
   version="0.8.0"
   long_usage=''
@@ -2170,6 +2279,7 @@ run() {
     "show") recipe_show_command ;;
     "update") recipe_update_command ;;
     "dir") recipe_dir_command ;;
+    "filter") recipe_filter_command ;;
   esac
 }
 
