feat: add bash & zsh completions

diff --git a/recipe b/recipe
--- a/recipe
+++ b/recipe
@@ -34,25 +34,26 @@ recipe_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "Recipe Book Commands:"
-  printf "  %s   Create and setup a new recipe book\n" "init  "
-  printf "  %s   Check your recipe book for potential problems\n" "doctor"
-  printf "  %s   Access git from your recipe book\n" "git   "
-  printf "  %s   Clone a remote git repository\n" "clone "
-  printf "  %s   Show recipe book directory\n" "dir   "
+  printf "  %s   Create and setup a new recipe book\n" "init       "
+  printf "  %s   Check your recipe book for potential problems\n" "doctor     "
+  printf "  %s   Access git from your recipe book\n" "git        "
+  printf "  %s   Clone a remote git repository\n" "clone      "
+  printf "  %s   Show recipe book directory\n" "dir        "
   echo
   printf "%s\n" "Recipe Commands:"
-  printf "  %s   Add a new recipe\n" "add   "
-  printf "  %s   List all your recipes\n" "list  "
-  printf "  %s   Use a recipe locally\n" "use   "
-  printf "  %s   Remove a recipe\n" "remove"
-  printf "  %s   Edit a recipe\n" "edit  "
-  printf "  %s   Show the content of a recipe\n" "show  "
-  printf "  %s   Interactively filter recipes\n" "filter"
+  printf "  %s   Add a new recipe\n" "add        "
+  printf "  %s   List all your recipes\n" "list       "
+  printf "  %s   Use a recipe locally\n" "use        "
+  printf "  %s   Remove a recipe\n" "remove     "
+  printf "  %s   Edit a recipe\n" "edit       "
+  printf "  %s   Show the content of a recipe\n" "show       "
+  printf "  %s   Interactively filter recipes\n" "filter     "
   echo
   printf "%s\n" "Commands:"
-  printf "  %s   Create a link to the recipe script\n" "link  "
-  printf "  %s   Remove the link to the recipe script\n" "unlink"
-  printf "  %s   Update recipe to the latest version\n" "update"
+  printf "  %s   Create a link to the recipe script\n" "link       "
+  printf "  %s   Remove the link to the recipe script\n" "unlink     "
+  printf "  %s   Update recipe to the latest version\n" "update     "
+  printf "  %s   Command line completions\n" "completions"
   echo
 
   # :command.long_usage
@@ -738,6 +739,40 @@ recipe_filter_usage() {
   fi
 }
 
+# :command.usage
+recipe_completions_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "recipe completions - Command line completions\n"
+    echo
+
+  else
+    printf "recipe completions - Command line completions\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  recipe completions\n"
+  printf "  recipe completions --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_examples
+    printf "%s\n" "Examples:"
+    printf "  eval \"$(recipe completions)\"\n"
+    echo
+
+  fi
+}
+
 # :command.normalize_input
 normalize_input() {
   local arg flags
@@ -891,6 +926,121 @@ run_git() {
 # src/lib/run_silent.sh
 run_silent() {
   command ${@} &> /dev/null
+}
+
+# src/lib/send_completions.sh
+send_completions() {
+  echo $'# recipe completion                                        -*- shell-script -*-'
+  echo $''
+  echo $'# This bash completions script was generated by'
+  echo $'# completely (https://github.com/dannyben/completely)'
+  echo $'# Modifying it manually is not recommended'
+  echo $''
+  echo $'_recipe_completions_filter() {'
+  echo $'  local words="$1"'
+  echo $'  local cur=${COMP_WORDS[COMP_CWORD]}'
+  echo $'  local result=()'
+  echo $''
+  echo $'  if [[ "${cur:0:1}" == "-" ]]; then'
+  echo $'    echo "$words"'
+  echo $'  '
+  echo $'  else'
+  echo $'    for word in $words; do'
+  echo $'      [[ "${word:0:1}" != "-" ]] && result+=("$word")'
+  echo $'    done'
+  echo $''
+  echo $'    echo "${result[*]}"'
+  echo $''
+  echo $'  fi'
+  echo $'}'
+  echo $''
+  echo $'_recipe_completions() {'
+  echo $'  local cur=${COMP_WORDS[COMP_CWORD]}'
+  echo $'  local compwords=("${COMP_WORDS[@]:1:$COMP_CWORD-1}")'
+  echo $'  local compline="${compwords[*]}"'
+  echo $''
+  echo $'  case "$compline" in'
+  echo $'    \'completions\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_recipe_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'doctor\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_recipe_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'filter\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_recipe_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'remove\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_recipe_completions_filter "--help --yes -h -y")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'unlink\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_recipe_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'update\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_recipe_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'clone\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_recipe_completions_filter "--help --yes -h -y")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'init\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_recipe_completions_filter "--help --yes -h -y")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'list\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_recipe_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'edit\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_recipe_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'link\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_recipe_completions_filter "--copy --help -c -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'show\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_recipe_completions_filter "--exec --help -e -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'add\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_recipe_completions_filter "--edit --force --help -e -f -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'git\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_recipe_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'use\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_recipe_completions_filter "--edit --help -e -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'dir\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_recipe_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'rm\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_recipe_completions_filter "--help --yes -h -y")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'ls\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_recipe_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    *)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_recipe_completions_filter "--help --version -h -v add clone completions dir doctor edit filter git init link list ls remove rm show unlink update use")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'  esac'
+  echo $'} &&'
+  echo $'complete -F _recipe_completions recipe'
+  echo $''
+  echo $'# ex: filetype=sh'
 }
 
 # src/lib/validations/validate_dir_exists.sh
@@ -1195,12 +1345,12 @@ recipe_show_command() {
 # :command.function
 recipe_update_command() {
   # src/update_command.sh
-  if [[ ! -d "${HOME}/.recipe" ]]; then
-      echo "No ~/.recipe directory. Check documentation for installation instruction."
+  if [[ ! -d "${RECIPE_INSTALL_DIR}" ]]; then
+      echo "No recipe directory. Check documentation for installation instruction."
       exit 1
   fi
 
-  git -C "${HOME}/.recipe" pull
+  run_git pull
 
 }
 
@@ -1217,6 +1367,13 @@ recipe_filter_command() {
   local recipes="$(find_recipe)"
 
   echo "${recipes}" | gum filter --placeholder "Select a recipe..."
+
+}
+
+# :command.function
+recipe_completions_command() {
+  # src/completions_command.sh
+  send_completions
 
 }
 
@@ -1376,6 +1533,13 @@ parse_requirements() {
       action="filter"
       shift
       recipe_filter_parse_requirements "$@"
+      shift $#
+      ;;
+
+    completions)
+      action="completions"
+      shift
+      recipe_completions_parse_requirements "$@"
       shift $#
       ;;
 
@@ -2332,9 +2496,53 @@ recipe_filter_parse_requirements() {
 
 }
 
+# :command.parse_requirements
+recipe_completions_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        recipe_completions_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="completions"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
 # :command.initialize
 initialize() {
-  version="0.9.1"
+  version="0.9.2"
   long_usage=''
   set -e
 
@@ -2371,6 +2579,7 @@ run() {
     "update") recipe_update_command ;;
     "dir") recipe_dir_command ;;
     "filter") recipe_filter_command ;;
+    "completions") recipe_completions_command ;;
   esac
 }
 
