feat: add unlink command

diff --git a/recipe b/recipe
--- a/recipe
+++ b/recipe
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.0.6 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.0.5 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
@@ -38,7 +38,8 @@ recipe_usage() {
   printf "  %s   Remove a recipe\n" "remove"
   printf "  %s   Edit a recipe\n" "edit  "
   printf "  %s   Clone a remote git repository\n" "clone "
-  printf "  %s   Create a symbolic link to the recipe script\n" "link  "
+  printf "  %s   Create a link to the recipe script\n" "link  "
+  printf "  %s   Remove the link to the recipe script\n" "unlink"
   printf "  %s   Show the content of a recipe\n" "show  "
   echo
 
@@ -419,11 +420,11 @@ recipe_clone_usage() {
 
 recipe_link_usage() {
   if [[ -n $long_usage ]]; then
-    printf "recipe link - Create a symbolic link to the recipe script\n"
+    printf "recipe link - Create a link to the recipe script\n"
     echo
 
   else
-    printf "recipe link - Create a symbolic link to the recipe script\n"
+    printf "recipe link - Create a link to the recipe script\n"
     echo
 
   fi
@@ -436,15 +437,6 @@ recipe_link_usage() {
   if [[ -n $long_usage ]]; then
     printf "%s\n" "Options:"
 
-    printf "  %s\n" "--remove, -r"
-    printf "    Remove the symbolic link instead\n"
-    echo
-
-    printf "  %s\n" "--source, -s SOURCE"
-    printf "    Path to the directory containing the recipe script\n"
-    printf "    Default: ${HOME}/.recipe\n"
-    echo
-
     printf "  %s\n" "--copy, -c"
     printf "    Copy the script instead of creating a symbolic link\n"
     echo
@@ -456,13 +448,51 @@ recipe_link_usage() {
     printf "%s\n" "Arguments:"
 
     printf "  %s\n" "PATH"
-    printf "    Path to the symbolic link\n"
+    printf "    Path to the link\n"
     printf "    Default: ${HOME}/.local/bin\n"
     echo
 
     printf "%s\n" "Examples:"
+    printf "  recipe link --copy\n"
     printf "  recipe link /usr/local/bin\n"
-    printf "  recipe link --source ~/scripts/recipe --remove\n"
+    echo
+
+  fi
+}
+
+recipe_unlink_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "recipe unlink - Remove the link to the recipe script\n"
+    echo
+
+  else
+    printf "recipe unlink - Remove the link to the recipe script\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  recipe unlink [PATH]\n"
+  printf "  recipe unlink --help | -h\n"
+  echo
+
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+    printf "%s\n" "Arguments:"
+
+    printf "  %s\n" "PATH"
+    printf "    Path to the link\n"
+    printf "    Default: ${HOME}/.local/bin\n"
+    echo
+
+    printf "%s\n" "Examples:"
+    printf "  recipe unlink\n"
+    printf "  recipe unlink /usr/local/bin\n"
     echo
 
   fi
@@ -662,7 +692,6 @@ run_git() {
 }
 
 run_silent() {
-  echo $@
   command ${@} &> /dev/null
 }
 
@@ -906,42 +935,41 @@ recipe_clone_command() {
 
 recipe_link_command() {
   local path="${args[path]}"
-
-  local source="${args[--source]}"
-  local remove="${args[--remove]}"
   local copy="${args[--copy]}"
 
-  if [[ -n "${remove}" ]]; then
-      if [[ -f "${path}/recipe" ]]; then
-          run_silent rm -rf "${path}/recipe"
-          echo "$(green ✔) Link removed from $(magenta "${path}")"
-      else
-          echo "No link found in $(magenta "${path}")"
-          exit 1
-      fi
+  if [[ -f "${path}/recipe" ]]; then
+      echo "There is already a link in $(magenta "${path}")"
+      exit 1
+  fi
+
+  local source="${HOME}/.recipe"
+
+  if [[ ! -d "${source}" ]]; then
+      echo "Source directory $(magenta "${source}") does not exist"
+      exit 1
+  fi
+
+  if [[ ! -f "${source}/recipe" ]]; then
+      echo "Script 'recipe' not found in $(magenta "${source}")"
+      exit 1
+  fi
+
+  local executable=`test -n "${copy}" && echo "cp" || echo "ln -s"`
+
+  run_silent ${executable} "${source}/recipe" "${path}/recipe"
+  echo "$(green ✔) Link created in $(magenta "${path}")"
+
+}
+
+recipe_unlink_command() {
+  local path="${args[path]}"
+
+  if [[ -f "${path}/recipe" ]]; then
+      run_silent rm -rf "${path}/recipe"
+      echo "$(green ✔) Link removed from $(magenta "${path}")"
   else
-      if [[ -f "${path}/recipe" ]]; then
-          echo "There is already a link in $(magenta "${path}")"
-          exit 1
-      fi
-
-      if [[ ! -d "${source}" ]]; then
-          echo "Source directory $(magenta "${source}") does not exist"
-          exit 1
-      fi
-
-      source=`realpath "${source}"`
-      echo "• Source directory: $(green "${source}")"
-
-      if [[ ! -f "${source}/recipe" ]]; then
-          echo "Script 'recipe' not found in $(magenta "${source}")"
-          exit 1
-      fi
-
-      local executable=`test -n "${copy}" && echo "cp" || echo "ln -s"`
-
-      command ${executable} "${source}/recipe" "${path}/recipe"
-      echo "$(green ✔) Link created in $(magenta "${path}")"
+      echo "No link found in $(magenta "${path}")"
+      exit 1
   fi
 
 }
@@ -1083,6 +1111,13 @@ parse_requirements() {
       action="link"
       shift
       recipe_link_parse_requirements "$@"
+      shift $#
+      ;;
+
+    unlink)
+      action="unlink"
+      shift
+      recipe_unlink_parse_requirements "$@"
       shift $#
       ;;
 
@@ -1689,25 +1724,6 @@ recipe_link_parse_requirements() {
     key="$1"
     case "$key" in
 
-      --remove | -r)
-
-        args['--remove']=1
-        shift
-        ;;
-
-      --source | -s)
-
-        if [[ -n ${2+x} ]]; then
-
-          args['--source']="$2"
-          shift
-          shift
-        else
-          printf "%s\n" "--source requires an argument: --source, -s SOURCE" >&2
-          exit 1
-        fi
-        ;;
-
       --copy | -c)
 
         args['--copy']=1
@@ -1736,7 +1752,54 @@ recipe_link_parse_requirements() {
   done
 
   [[ -n ${args['path']:-} ]] || args['path']="${HOME}/.local/bin"
-  [[ -n ${args['--source']:-} ]] || args['--source']="${HOME}/.recipe"
+
+}
+
+recipe_unlink_parse_requirements() {
+
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        recipe_unlink_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  action="unlink"
+
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+
+        if [[ -z ${args['path']+x} ]]; then
+
+          args['path']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
+
+        ;;
+
+    esac
+  done
+
+  [[ -n ${args['path']:-} ]] || args['path']="${HOME}/.local/bin"
 
 }
 
@@ -1806,7 +1869,7 @@ recipe_show_parse_requirements() {
 }
 
 initialize() {
-  version="0.5.0"
+  version="0.6.0"
   long_usage=''
   set -e
 
@@ -1834,6 +1897,7 @@ run() {
     "edit") recipe_edit_command ;;
     "clone") recipe_clone_command ;;
     "link") recipe_link_command ;;
+    "unlink") recipe_unlink_command ;;
     "show") recipe_show_command ;;
   esac
 }
