style: add color to bashly error messages

diff --git a/recipe b/recipe
--- a/recipe
+++ b/recipe
@@ -3,7 +3,7 @@
 # Modifying it manually is not recommended
 
 if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
-  printf "bash version 4 or higher is required\n" >&2
+  printf "$(red pm:) bash version 4 or higher is required\n" >&2
   exit 1
 fi
 
@@ -1105,14 +1105,14 @@ parse_requirements() {
   if command -v git >/dev/null 2>&1; then
     deps['git']="$(command -v git | head -n1)"
   else
-    printf "missing dependency: git\n" >&2
+    printf "$(red pm:) missing dependency: git\n" >&2
     exit 1
   fi
 
   if command -v gum >/dev/null 2>&1; then
     deps['gum']="$(command -v gum | head -n1)"
   else
-    printf "missing dependency: gum\n" >&2
+    printf "$(red pm:) missing dependency: gum\n" >&2
     exit 1
   fi
 
@@ -1246,7 +1246,7 @@ parse_requirements() {
       ;;
 
     *)
-      printf "invalid command: %s\n" "$action" >&2
+      printf "$(red pm:) invalid command: %s\n" "$action" >&2
       exit 1
       ;;
 
@@ -1257,13 +1257,13 @@ parse_requirements() {
     case "$key" in
 
       -?*)
-        printf "invalid option: %s\n" "$key" >&2
+        printf "$(red pm:) invalid option: %s\n" "$key" >&2
         exit 1
         ;;
 
       *)
 
-        printf "invalid argument: %s\n" "$key" >&2
+        printf "$(red pm:) invalid argument: %s\n" "$key" >&2
         exit 1
 
         ;;
@@ -1297,7 +1297,7 @@ recipe_add_parse_requirements() {
     case "$key" in
 
       -?*)
-        printf "invalid option: %s\n" "$key" >&2
+        printf "$(red pm:) invalid option: %s\n" "$key" >&2
         exit 1
         ;;
 
@@ -1311,7 +1311,7 @@ recipe_add_parse_requirements() {
           args['name']=$1
           shift
         else
-          printf "invalid argument: %s\n" "$key" >&2
+          printf "$(red pm:) invalid argument: %s\n" "$key" >&2
           exit 1
         fi
 
@@ -1321,18 +1321,18 @@ recipe_add_parse_requirements() {
   done
 
   if [[ -z ${args['file']+x} ]]; then
-    printf "missing required argument: FILE\nusage: recipe add FILE [NAME]\n" >&2
+    printf "$(red pm:) missing required argument: FILE\nusage: recipe add FILE [NAME]\n" >&2
 
     exit 1
   fi
 
   if [[ -v args['file'] && -n $(validate_file_exists "${args['file']:-}") ]]; then
-    printf "validation error in %s:\n%s\n" "FILE" "$(validate_file_exists "${args['file']:-}")" >&2
+    printf "$(red pm:) validation error in %s:\n%s\n" "FILE" "$(validate_file_exists "${args['file']:-}")" >&2
     exit 1
   fi
 
   if [[ -v args['name'] && -n $(validate_recipe_is_missing "${args['name']:-}") ]]; then
-    printf "validation error in %s:\n%s\n" "NAME" "$(validate_recipe_is_missing "${args['name']:-}")" >&2
+    printf "$(red pm:) validation error in %s:\n%s\n" "NAME" "$(validate_recipe_is_missing "${args['name']:-}")" >&2
     exit 1
   fi
 
@@ -1374,13 +1374,13 @@ recipe_list_parse_requirements() {
     case "$key" in
 
       -?*)
-        printf "invalid option: %s\n" "$key" >&2
+        printf "$(red pm:) invalid option: %s\n" "$key" >&2
         exit 1
         ;;
 
       *)
 
-        printf "invalid argument: %s\n" "$key" >&2
+        printf "$(red pm:) invalid argument: %s\n" "$key" >&2
         exit 1
 
         ;;
@@ -1426,13 +1426,13 @@ recipe_filter_parse_requirements() {
     case "$key" in
 
       -?*)
-        printf "invalid option: %s\n" "$key" >&2
+        printf "$(red pm:) invalid option: %s\n" "$key" >&2
         exit 1
         ;;
 
       *)
 
-        printf "invalid argument: %s\n" "$key" >&2
+        printf "$(red pm:) invalid argument: %s\n" "$key" >&2
         exit 1
 
         ;;
@@ -1478,7 +1478,7 @@ recipe_use_parse_requirements() {
     case "$key" in
 
       -?*)
-        printf "invalid option: %s\n" "$key" >&2
+        printf "$(red pm:) invalid option: %s\n" "$key" >&2
         exit 1
         ;;
 
@@ -1492,7 +1492,7 @@ recipe_use_parse_requirements() {
           args['destination']=$1
           shift
         else
-          printf "invalid argument: %s\n" "$key" >&2
+          printf "$(red pm:) invalid argument: %s\n" "$key" >&2
           exit 1
         fi
 
@@ -1502,13 +1502,13 @@ recipe_use_parse_requirements() {
   done
 
   if [[ -z ${args['recipe']+x} ]]; then
-    printf "missing required argument: RECIPE\nusage: recipe use RECIPE [DESTINATION]\n" >&2
+    printf "$(red pm:) missing required argument: RECIPE\nusage: recipe use RECIPE [DESTINATION]\n" >&2
 
     exit 1
   fi
 
   if [[ -v args['recipe'] && -n $(validate_recipe_exists "${args['recipe']:-}") ]]; then
-    printf "validation error in %s:\n%s\n" "RECIPE" "$(validate_recipe_exists "${args['recipe']:-}")" >&2
+    printf "$(red pm:) validation error in %s:\n%s\n" "RECIPE" "$(validate_recipe_exists "${args['recipe']:-}")" >&2
     exit 1
   fi
 
@@ -1556,7 +1556,7 @@ recipe_remove_parse_requirements() {
     case "$key" in
 
       -?*)
-        printf "invalid option: %s\n" "$key" >&2
+        printf "$(red pm:) invalid option: %s\n" "$key" >&2
         exit 1
         ;;
 
@@ -1566,7 +1566,7 @@ recipe_remove_parse_requirements() {
           args['name']=$1
           shift
         else
-          printf "invalid argument: %s\n" "$key" >&2
+          printf "$(red pm:) invalid argument: %s\n" "$key" >&2
           exit 1
         fi
 
@@ -1576,13 +1576,13 @@ recipe_remove_parse_requirements() {
   done
 
   if [[ -z ${args['name']+x} ]]; then
-    printf "missing required argument: NAME\nusage: recipe remove NAME\n" >&2
+    printf "$(red pm:) missing required argument: NAME\nusage: recipe remove NAME\n" >&2
 
     exit 1
   fi
 
   if [[ -v args['name'] && -n $(validate_recipe_exists "${args['name']:-}") ]]; then
-    printf "validation error in %s:\n%s\n" "NAME" "$(validate_recipe_exists "${args['name']:-}")" >&2
+    printf "$(red pm:) validation error in %s:\n%s\n" "NAME" "$(validate_recipe_exists "${args['name']:-}")" >&2
     exit 1
   fi
 
@@ -1630,7 +1630,7 @@ recipe_edit_parse_requirements() {
     case "$key" in
 
       -?*)
-        printf "invalid option: %s\n" "$key" >&2
+        printf "$(red pm:) invalid option: %s\n" "$key" >&2
         exit 1
         ;;
 
@@ -1640,7 +1640,7 @@ recipe_edit_parse_requirements() {
           args['name']=$1
           shift
         else
-          printf "invalid argument: %s\n" "$key" >&2
+          printf "$(red pm:) invalid argument: %s\n" "$key" >&2
           exit 1
         fi
 
@@ -1650,13 +1650,13 @@ recipe_edit_parse_requirements() {
   done
 
   if [[ -z ${args['name']+x} ]]; then
-    printf "missing required argument: NAME\nusage: recipe edit NAME\n" >&2
+    printf "$(red pm:) missing required argument: NAME\nusage: recipe edit NAME\n" >&2
 
     exit 1
   fi
 
   if [[ -v args['name'] && -n $(validate_recipe_exists "${args['name']:-}") ]]; then
-    printf "validation error in %s:\n%s\n" "NAME" "$(validate_recipe_exists "${args['name']:-}")" >&2
+    printf "$(red pm:) validation error in %s:\n%s\n" "NAME" "$(validate_recipe_exists "${args['name']:-}")" >&2
     exit 1
   fi
 
@@ -1710,13 +1710,13 @@ recipe_show_parse_requirements() {
           shift
           shift
         else
-          printf "%s\n" "--exec requires an argument: --exec, -x EXECUTABLE" >&2
+          printf "%s\n" "$(red pm:) --exec requires an argument: --exec, -x EXECUTABLE" >&2
           exit 1
         fi
         ;;
 
       -?*)
-        printf "invalid option: %s\n" "$key" >&2
+        printf "$(red pm:) invalid option: %s\n" "$key" >&2
         exit 1
         ;;
 
@@ -1726,7 +1726,7 @@ recipe_show_parse_requirements() {
           args['name']=$1
           shift
         else
-          printf "invalid argument: %s\n" "$key" >&2
+          printf "$(red pm:) invalid argument: %s\n" "$key" >&2
           exit 1
         fi
 
@@ -1736,7 +1736,7 @@ recipe_show_parse_requirements() {
   done
 
   if [[ -z ${args['name']+x} ]]; then
-    printf "missing required argument: NAME\nusage: recipe show NAME [OPTIONS]\n" >&2
+    printf "$(red pm:) missing required argument: NAME\nusage: recipe show NAME [OPTIONS]\n" >&2
 
     exit 1
   fi
@@ -1744,7 +1744,7 @@ recipe_show_parse_requirements() {
   [[ -n ${args['--exec']:-} ]] || args['--exec']="${RECIPE_SHOW_CMD}"
 
   if [[ -v args['name'] && -n $(validate_recipe_exists "${args['name']:-}") ]]; then
-    printf "validation error in %s:\n%s\n" "NAME" "$(validate_recipe_exists "${args['name']:-}")" >&2
+    printf "$(red pm:) validation error in %s:\n%s\n" "NAME" "$(validate_recipe_exists "${args['name']:-}")" >&2
     exit 1
   fi
 
@@ -1792,13 +1792,13 @@ recipe_env_parse_requirements() {
     case "$key" in
 
       -?*)
-        printf "invalid option: %s\n" "$key" >&2
+        printf "$(red pm:) invalid option: %s\n" "$key" >&2
         exit 1
         ;;
 
       *)
 
-        printf "invalid argument: %s\n" "$key" >&2
+        printf "$(red pm:) invalid argument: %s\n" "$key" >&2
         exit 1
 
         ;;
@@ -1838,13 +1838,13 @@ recipe_status_parse_requirements() {
         ;;
 
       -?*)
-        printf "invalid option: %s\n" "$key" >&2
+        printf "$(red pm:) invalid option: %s\n" "$key" >&2
         exit 1
         ;;
 
       *)
 
-        printf "invalid argument: %s\n" "$key" >&2
+        printf "$(red pm:) invalid argument: %s\n" "$key" >&2
         exit 1
 
         ;;
@@ -1890,13 +1890,13 @@ recipe_stage_parse_requirements() {
     case "$key" in
 
       -?*)
-        printf "invalid option: %s\n" "$key" >&2
+        printf "$(red pm:) invalid option: %s\n" "$key" >&2
         exit 1
         ;;
 
       *)
 
-        printf "invalid argument: %s\n" "$key" >&2
+        printf "$(red pm:) invalid argument: %s\n" "$key" >&2
         exit 1
 
         ;;
@@ -1942,13 +1942,13 @@ recipe_unstage_parse_requirements() {
     case "$key" in
 
       -?*)
-        printf "invalid option: %s\n" "$key" >&2
+        printf "$(red pm:) invalid option: %s\n" "$key" >&2
         exit 1
         ;;
 
       *)
 
-        printf "invalid argument: %s\n" "$key" >&2
+        printf "$(red pm:) invalid argument: %s\n" "$key" >&2
         exit 1
 
         ;;
@@ -1994,13 +1994,13 @@ recipe_restore_parse_requirements() {
     case "$key" in
 
       -?*)
-        printf "invalid option: %s\n" "$key" >&2
+        printf "$(red pm:) invalid option: %s\n" "$key" >&2
         exit 1
         ;;
 
       *)
 
-        printf "invalid argument: %s\n" "$key" >&2
+        printf "$(red pm:) invalid argument: %s\n" "$key" >&2
         exit 1
 
         ;;
@@ -2052,13 +2052,13 @@ recipe_diff_parse_requirements() {
         ;;
 
       -?*)
-        printf "invalid option: %s\n" "$key" >&2
+        printf "$(red pm:) invalid option: %s\n" "$key" >&2
         exit 1
         ;;
 
       *)
 
-        printf "invalid argument: %s\n" "$key" >&2
+        printf "$(red pm:) invalid argument: %s\n" "$key" >&2
         exit 1
 
         ;;
@@ -2104,7 +2104,7 @@ recipe_commit_parse_requirements() {
     case "$key" in
 
       -?*)
-        printf "invalid option: %s\n" "$key" >&2
+        printf "$(red pm:) invalid option: %s\n" "$key" >&2
         exit 1
         ;;
 
@@ -2114,7 +2114,7 @@ recipe_commit_parse_requirements() {
           args['message']=$1
           shift
         else
-          printf "invalid argument: %s\n" "$key" >&2
+          printf "$(red pm:) invalid argument: %s\n" "$key" >&2
           exit 1
         fi
 
@@ -2161,13 +2161,13 @@ recipe_cd_parse_requirements() {
     case "$key" in
 
       -?*)
-        printf "invalid option: %s\n" "$key" >&2
+        printf "$(red pm:) invalid option: %s\n" "$key" >&2
         exit 1
         ;;
 
       *)
 
-        printf "invalid argument: %s\n" "$key" >&2
+        printf "$(red pm:) invalid argument: %s\n" "$key" >&2
         exit 1
 
         ;;
@@ -2234,7 +2234,7 @@ recipe_git_parse_requirements() {
   done
 
   if [[ ${#other_args[@]} -eq 0 ]]; then
-    printf "missing required argument: COMMANDS...\nusage: recipe git [--] COMMANDS...\n" >&2
+    printf "$(red pm:) missing required argument: COMMANDS...\nusage: recipe git [--] COMMANDS...\n" >&2
     exit 1
   fi
 
@@ -2308,7 +2308,7 @@ recipe_book_parse_requirements() {
       ;;
 
     *)
-      printf "invalid command: %s\n" "$action" >&2
+      printf "$(red pm:) invalid command: %s\n" "$action" >&2
       exit 1
       ;;
 
@@ -2319,13 +2319,13 @@ recipe_book_parse_requirements() {
     case "$key" in
 
       -?*)
-        printf "invalid option: %s\n" "$key" >&2
+        printf "$(red pm:) invalid option: %s\n" "$key" >&2
         exit 1
         ;;
 
       *)
 
-        printf "invalid argument: %s\n" "$key" >&2
+        printf "$(red pm:) invalid argument: %s\n" "$key" >&2
         exit 1
 
         ;;
@@ -2359,13 +2359,13 @@ recipe_book_list_parse_requirements() {
     case "$key" in
 
       -?*)
-        printf "invalid option: %s\n" "$key" >&2
+        printf "$(red pm:) invalid option: %s\n" "$key" >&2
         exit 1
         ;;
 
       *)
 
-        printf "invalid argument: %s\n" "$key" >&2
+        printf "$(red pm:) invalid argument: %s\n" "$key" >&2
         exit 1
 
         ;;
@@ -2399,7 +2399,7 @@ recipe_book_global_parse_requirements() {
     case "$key" in
 
       -?*)
-        printf "invalid option: %s\n" "$key" >&2
+        printf "$(red pm:) invalid option: %s\n" "$key" >&2
         exit 1
         ;;
 
@@ -2409,7 +2409,7 @@ recipe_book_global_parse_requirements() {
           args['recipe-book']=$1
           shift
         else
-          printf "invalid argument: %s\n" "$key" >&2
+          printf "$(red pm:) invalid argument: %s\n" "$key" >&2
           exit 1
         fi
 
@@ -2419,13 +2419,13 @@ recipe_book_global_parse_requirements() {
   done
 
   if [[ -z ${args['recipe-book']+x} ]]; then
-    printf "missing required argument: RECIPE-BOOK\nusage: recipe book global RECIPE-BOOK\n" >&2
+    printf "$(red pm:) missing required argument: RECIPE-BOOK\nusage: recipe book global RECIPE-BOOK\n" >&2
 
     exit 1
   fi
 
   if [[ -v args['recipe-book'] && -n $(validate_recipe_book_exists "${args['recipe-book']:-}") ]]; then
-    printf "validation error in %s:\n%s\n" "RECIPE-BOOK" "$(validate_recipe_book_exists "${args['recipe-book']:-}")" >&2
+    printf "$(red pm:) validation error in %s:\n%s\n" "RECIPE-BOOK" "$(validate_recipe_book_exists "${args['recipe-book']:-}")" >&2
     exit 1
   fi
 
@@ -2455,7 +2455,7 @@ recipe_book_local_parse_requirements() {
     case "$key" in
 
       -?*)
-        printf "invalid option: %s\n" "$key" >&2
+        printf "$(red pm:) invalid option: %s\n" "$key" >&2
         exit 1
         ;;
 
@@ -2465,7 +2465,7 @@ recipe_book_local_parse_requirements() {
           args['recipe-book']=$1
           shift
         else
-          printf "invalid argument: %s\n" "$key" >&2
+          printf "$(red pm:) invalid argument: %s\n" "$key" >&2
           exit 1
         fi
 
@@ -2475,13 +2475,13 @@ recipe_book_local_parse_requirements() {
   done
 
   if [[ -z ${args['recipe-book']+x} ]]; then
-    printf "missing required argument: RECIPE-BOOK\nusage: recipe book local RECIPE-BOOK\n" >&2
+    printf "$(red pm:) missing required argument: RECIPE-BOOK\nusage: recipe book local RECIPE-BOOK\n" >&2
 
     exit 1
   fi
 
   if [[ -v args['recipe-book'] && -n $(validate_recipe_book_exists "${args['recipe-book']:-}") ]]; then
-    printf "validation error in %s:\n%s\n" "RECIPE-BOOK" "$(validate_recipe_book_exists "${args['recipe-book']:-}")" >&2
+    printf "$(red pm:) validation error in %s:\n%s\n" "RECIPE-BOOK" "$(validate_recipe_book_exists "${args['recipe-book']:-}")" >&2
     exit 1
   fi
 
@@ -2511,7 +2511,7 @@ recipe_book_add_parse_requirements() {
     case "$key" in
 
       -?*)
-        printf "invalid option: %s\n" "$key" >&2
+        printf "$(red pm:) invalid option: %s\n" "$key" >&2
         exit 1
         ;;
 
@@ -2525,7 +2525,7 @@ recipe_book_add_parse_requirements() {
           args['repository']=$1
           shift
         else
-          printf "invalid argument: %s\n" "$key" >&2
+          printf "$(red pm:) invalid argument: %s\n" "$key" >&2
           exit 1
         fi
 
@@ -2535,13 +2535,13 @@ recipe_book_add_parse_requirements() {
   done
 
   if [[ -z ${args['recipe-book']+x} ]]; then
-    printf "missing required argument: RECIPE-BOOK\nusage: recipe book add RECIPE-BOOK [REPOSITORY]\n" >&2
+    printf "$(red pm:) missing required argument: RECIPE-BOOK\nusage: recipe book add RECIPE-BOOK [REPOSITORY]\n" >&2
 
     exit 1
   fi
 
   if [[ -v args['recipe-book'] && -n $(validate_recipe_book_is_missing "${args['recipe-book']:-}") ]]; then
-    printf "validation error in %s:\n%s\n" "RECIPE-BOOK" "$(validate_recipe_book_is_missing "${args['recipe-book']:-}")" >&2
+    printf "$(red pm:) validation error in %s:\n%s\n" "RECIPE-BOOK" "$(validate_recipe_book_is_missing "${args['recipe-book']:-}")" >&2
     exit 1
   fi
 
